name: unit-tests
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - run: go vet ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - run: go test -v -race ./...
